### ISSUE TITLE
Help/Guidance running XBMC on Boxeebox

### ISSUE THREAD

**Issue by Rogaran** [quarnster/boxeebox-xbmc#158]
After following the instructions here: https://smyl.es/how-to-obtain-root-install-and-run-xbmc-on-d-link-boxee-box/, I have XBMC running on my BB, but have so far been unsuccessful adding the contents of the hard drive connected to my BB. XBMC seems unable to see or find the hard drive. There is an option to describe the path to the hard drive, but not knowing what that is or how to find it is an issue. In addition, I have no idea or information on how to fit XBMC to the screen on my television, are there settings that can be modified? Essentially general information on working with XBMC on the Boxeebox is what I need.

**Comment by cigamit** [comment]
This area is for issues.  Please ask for help on the official forums for XBMC on Boxee Help
http://boxeed.in/forums/viewforum.php?f=13
